### ISSUE TITLE
[Bug]: Support for VariantCraftingTables is broken

### ISSUE THREAD

**Issue by Leronus** [Fuzss/visualworkbench#29]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.3

### Notes (Required)

Current behaviour: Visual workbench is not applied to modded crafting tables
Steps to reproduce:
 1. Install [VariantCraftingTables 1.7.2 for 1.19.2](https://www.curseforge.com/minecraft/mc-mods/variant-crafting-tables/files/4346952)
 2. Craft a modded crafting table (such as Spruce Crafting Table; tag: "vct_spruce_crafting_table")*
 3. Open the crafting table
 4. Place items inside crafting table
 5. Close crafting table gui

The items will return to the players inventory instead of staying inside the crafting table and being rendered above.

*This item tag is present in the configuration file for visual workbench, implying it **should** work with this modded crafting table.

**Comment by Fuzss** [comment]
Fixed in latest version.

**Comment by Leronus** [comment]
The items are stored in the modded crafting tables now, but the items are still not visually rendering above with the latest version.
Thankyou for the quick update, being able to store the items in the table is already a big improvement

**Comment by Fuzss** [comment]
Try replacing the crafting tables. I specifically tested the new version with VCT and all was working fine.

**Comment by Leronus** [comment]
I had edited the config for testing, after deleting it it is all working as intended. Thank you very much, this is an awesome mod.

**Comment by Fuzss** [comment]
Glad you like it!
